### ISSUE TITLE
rootProject.name is case sensitive in latest Android Studio versions

### ISSUE THREAD

**Issue by salpiras** [blundell/polkiemon#1]
Hi Paul! 

I was trying to run the project with one of the latest versions of Android Studio (Iguana 2023.2.1) and I got an "IllegalStateException: Module entity polkiemon.app.androidTest should be available" while syncing - it seems like it's caused by rootProject.name being treated as case sensitive in the later versions of AS so reverting rootProject.name to lowercase "polkiemon" in settings.gradle fixes the issue.

Not sure if this repo is open to PRs so I thought to flag it in issues first, thanks so much for your repo and your articles, they have been a great resource!

**Comment by blundell** [comment]
thanks for that!

Just reproduced:

![image](https://github.com/blundell/polkiemon/assets/655860/6bc255eb-2ef4-4eab-8378-3a54b32d3a34)


& pushed the fix 👍
